config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'general#top'

  devise_for :users
  devise_for :admins, path: 'admin'

  get :profile, to: 'users/settings#profile'

  namespace :admin do
    root 'general#dashboard'
    resources :users, only: %i(index)
    resources :fields, only: %i(index new create)
  end
end

app/models/admin.rb
# frozen_string_literal: true

# What Admin Can Do
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

# Common ActiveRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/field.rb
# frozen_string_literal: true

# Field behaves
class Field < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

# Code for users
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  validates :username, :gender, :birthday, presence: true
  validates :username, length: { in: 2..25, allow_blank: true },
                       format: { with: /\A[a-z][a-z0-9_\-\s]*\z/i,
                                 allow_blank: true }
  validate :in_valid_birthday_range

  enum gender: %i[male female not_both]

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def age
    year = ((Date.today.to_s(:number).to_i - birthday.to_s(:number).to_i) /
            10_000.0)
    year.to_i == year ? year + 1 : year.ceil
  end

  private

  def in_valid_birthday_range
    errors.add(:birthday, :not_in_range) unless
      ((Date.today - 90.years)..(Date.today - 1.day)).cover? birthday
  end
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

# Common Controller for Admin
class Admin::ApplicationController < ApplicationController
  layout 'admin'

  before_action :authenticate_admin!
end

app/controllers/admin/fields_controller.rb
# frozen_string_literal: true

# Field Actions
class Admin::FieldsController < Admin::ApplicationController
  def index
    @fields = Field.order(:id)
  end

  def new
    @field = Field.new
  end

  def create
    @field = Field.new field_params
    if @field.save
      redirect_to admin_fields_path, notice: 'Đã thêm lĩnh vực mới'
    else
      flash.now[:alert] = 'Không thêm được lĩnh vực'
      render :new
    end
  end

  private

  def field_params
    params.require(:field).permit(:name)
  end
end

app/controllers/admin/general_controller.rb
# frozen_string_literal: true

# Admin General Actions
class Admin::GeneralController < Admin::ApplicationController
  def dashboard; end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

# User Actions
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = User.order(:id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Common for controllers
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[username gender birthday])
  end

  private

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    end
  end
end

app/controllers/general_controller.rb
# frozen_string_literal: true

# Define some static pages
class GeneralController < ApplicationController
  def top; end
end

app/controllers/users/application_controller.rb
# frozen_string_literal: true

class Users::ApplicationController < ApplicationController
end

app/controllers/users/settings_controller.rb
# frozen_string_literal: true

# User Settings
class Users::SettingsController < Users::ApplicationController
  def profile; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper for views
module ApplicationHelper
end

app/views/admin/fields/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1 class="mb-3">Lĩnh vực</h1>
  <%= link_to 'Thêm', new_admin_field_path, class: 'btn btn-primary' %>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tên</th>
      <th scope="col">Số bài</th>
      <th scope="col">Ngày tạo</th>
    </tr>
  </thead>
  <tbody>
    <% @fields.each do |f| %>
      <tr>
        <th scope="row"><%= f.id %></th>
        <td><%= f.name %></td>
        <td><%= f.lessons_count %></td>
        <td><%= l f.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/fields/new.html.erb
<h1 class="mb-4">Thêm lĩnh vực mới</h1>
<%= form_with model: [:admin, @field], local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/admin/general/dashboard.html.erb
<h1>Dashboard</h1>

app/views/admin/users/index.html.erb
<h1 class="mb-3">Người dùng</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Tuổi</th>
      <th scope="col">Giới Tính</th>
      <th scope="col">Ngày tham gia</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      <tr>
        <th scope="row"><%= u.id %></th>
        <td><%= u.username %></td>
        <td><%= u.email %></td>
        <td><%= u.age %></td>
        <td><%= u.gender %></td>
        <td><%= l u.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="vi">
  <head>
    <title>Angilr Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/admin_header' %>
    <%= render 'shared/flash' %>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="vi">
  <head>
    <title>Angilr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="vi">
  <head>
    <title>Angilr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
          <%= link_to root_path do %>
            <%= image_tag 'logo', width: 150, class: "mx-auto d-block" %>
          <% end %>

          <%= yield %>

          <div class="text-center">
            <%= render "users/shared/links" %>
          </div>
        </div>
        <div class="col-lg-4"></div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to admin_root_path, class: "navbar-brand" do %>
      <strong>Angilr Admin</strong>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Người dùng', admin_users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Lĩnh vực', admin_fields_path, class: 'nav-link' %>
        </li>
      </ul>
      <div>
        <% if admin_signed_in? %>
          <%= link_to "Thoát", destroy_admin_session_path, class: "btn btn-dark" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_flash.html.erb
<% if notice %>
  <p class="alert alert-info text-center"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger text-center"><%= alert %></p>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to root_path, class: "navbar-brand" do %>
      <strong>Angilr</strong>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> -->
      </ul>
      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
      <div>
        <% if user_signed_in? %>
          <span class="nav-item dropdown mr-3">
            <a class="dropdown-toggle" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <em><%= current_user.username %></em>
            </a>
            <div class="dropdown-menu" aria-labelledby="profileDropdown">
              <%= link_to "Thông tin cá nhân", profile_path, class: "dropdown-item" %>
            </div>
          </span>
          <%= link_to "Thoát", destroy_user_session_path, class: "btn btn-dark" %>
        <% else %>
          <%= link_to "Đăng ký", new_user_registration_path, class: "btn btn-dark" %>
          <%= link_to "Đăng nhập", new_user_session_path, class: "btn btn-light" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/users/settings/profile.html.erb
<h1 class="text-center mb-3">Thông tin cá nhân</h1>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <h5 class="alert-heading text-center">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h5>
    <ul class="mb-0">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('user.login'), new_session_path(resource_name), class: 'mb-3' %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('user.sign_up'), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t('user.forgot_password'), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('user.not_receive_confirmation_instruction'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('user.not_receive_unlock_instruction'), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('user.sign_in_with', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>